import Mathlib.Data.ZMod.Basic
import Mathlib.GroupTheory.Index
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.Tactic.Abel
import Mathlib.Tactic.Ring

/-!
# Finite residue-itinerary certificates for generalized Collatz branches

This file isolates the finite-level algebra used by
`CLM-COL-000016`, `CLM-COL-000017`, `MOR-COL-000006`, and
`PO-COL-000003`.

The modulus is an arbitrary positive natural number; it is not assumed prime.
The branch data retain the integer multiplier `m_i`, integer offset `r_i`, and
the exact integer value `T(i)`.  No replacement by a normalized fraction is
made.

This certificate deliberately stops at the one-digit lifting kernel.  It proves
the affine permutation used at every node of the finite itinerary tree and the
exact attainable-range cardinality and exact cardinality of every nonempty
fibre.  It does not formalize the inverse limit or the infinite `d`-adic
inverse series.
-/

namespace CollatzReconstruction.GeneralizedResidueItinerary

open Function Set

/-- Literal branch data for a modulus-`d` Matthews map.

`branchValue i` is the integer `T(i)`.  The final field is the exact
divisibility identity which says that `(m_i * i - r_i) / d = T(i)` without
normalizing any of the three integer parameters. -/
structure BranchData (d : ℕ) where
  multiplier : Fin d → ℤ
  offset : Fin d → ℤ
  branchValue : Fin d → ℤ
  multiplier_ne_zero : ∀ i, multiplier i ≠ 0
  branch_identity : ∀ i,
    multiplier i * (i.1 : ℤ) - offset i = (d : ℤ) * branchValue i

variable {d : ℕ}

/-- The integer numerator identity on the lift `i + d*t`.

After division by `d`, this is the unnormalized equality
`T(i + d*t) = T(i) + m_i*t`. -/
theorem branch_numerator_on_lift (B : BranchData d) (i : Fin d) (t : ℤ) :
    B.multiplier i * ((i.1 : ℤ) + (d : ℤ) * t) - B.offset i =
      (d : ℤ) * (B.branchValue i + B.multiplier i * t) := by
  calc
    B.multiplier i * ((i.1 : ℤ) + (d : ℤ) * t) - B.offset i =
        (B.multiplier i * (i.1 : ℤ) - B.offset i) +
          B.multiplier i * (d : ℤ) * t := by ring
    _ = (d : ℤ) * B.branchValue i + B.multiplier i * (d : ℤ) * t := by
      rw [B.branch_identity i]
    _ = (d : ℤ) * (B.branchValue i + B.multiplier i * t) := by ring

/-- The second itinerary digit of the lift `i + d*t`, reduced modulo `d`. -/
def nextDigit (B : BranchData d) (i : Fin d) (t : ZMod d) : ZMod d :=
  (B.branchValue i : ZMod d) + (B.multiplier i : ZMod d) * t

/-- Translation after multiplication by a unit is an explicit permutation.

The inverse is kept in coordinates instead of hidden behind finite-cardinality
reasoning. -/
def affineUnitEquiv (b : ZMod d) (u : (ZMod d)ˣ) : ZMod d ≃ ZMod d where
  toFun t := b + (u : ZMod d) * t
  invFun y := (↑(u⁻¹) : ZMod d) * (y - b)
  left_inv t := by
    simp
  right_inv y := by
    simp [mul_sub]

/-- Unit multipliers give a bijection from the `d` input lifts of a branch to
all `d` possible next digits.  This is the exact induction kernel for the
finite-level residue-itinerary permutation. -/
theorem nextDigit_bijective_of_isUnit (B : BranchData d) (i : Fin d)
    (hunit : IsUnit (B.multiplier i : ZMod d)) :
    Bijective (nextDigit B i) := by
  rcases hunit with ⟨u, hu⟩
  have hfun : nextDigit B i = fun t ↦
      (B.branchValue i : ZMod d) + (u : ZMod d) * t := by
    funext t
    simp only [nextDigit]
    rw [hu]
  rw [hfun]
  exact (affineUnitEquiv (B.branchValue i : ZMod d) u).bijective

/-- The range of multiplication by `a` is the cyclic additive subgroup
generated by `a`, with no primality assumption on `d`. -/
def mulRangeEquivZMultiples (a : ZMod d) :
    {y : ZMod d // y ∈ Set.range (fun t : ZMod d ↦ a * t)} ≃
      AddSubgroup.zmultiples a where
  toFun y := by
    refine ⟨y.1, ?_⟩
    rcases y.2 with ⟨t, ht⟩
    obtain ⟨z, rfl⟩ := ZMod.intCast_surjective t
    rw [AddSubgroup.mem_zmultiples_iff]
    refine ⟨z, ?_⟩
    rw [← ht]
    simp [zsmul_eq_mul, mul_comm]
  invFun y := by
    refine ⟨y.1, ?_⟩
    have hy := y.2
    rw [AddSubgroup.mem_zmultiples_iff] at hy
    rcases hy with ⟨z, hz⟩
    refine ⟨(z : ZMod d), ?_⟩
    rw [← hz]
    simp [zsmul_eq_mul, mul_comm]
  left_inv y := by
    apply Subtype.ext
    rfl
  right_inv y := by
    apply Subtype.ext
    rfl

/-- Adding a fixed branch value does not change the cardinality of the
attainable-next-digit type. -/
def translateMulRangeEquiv (b a : ZMod d) :
    {y : ZMod d // y ∈ Set.range (fun t : ZMod d ↦ a * t)} ≃
      {y : ZMod d // y ∈ Set.range (fun t : ZMod d ↦ b + a * t)} where
  toFun y := ⟨b + y.1, by
    rcases y.2 with ⟨t, ht⟩
    refine ⟨t, ?_⟩
    change b + a * t = b + y.1
    exact congrArg (fun z ↦ b + z) ht⟩
  invFun y := ⟨y.1 - b, by
    rcases y.2 with ⟨t, ht⟩
    refine ⟨t, ?_⟩
    calc
      a * t = (b + a * t) - b := by abel
      _ = y.1 - b := congrArg (fun z ↦ z - b) ht⟩
  left_inv y := by
    apply Subtype.ext
    simp
  right_inv y := by
    apply Subtype.ext
    simp

/-- Multiplication by `a` as an additive endomorphism of `ZMod d`. -/
def mulAddHom (a : ZMod d) : ZMod d →+ ZMod d where
  toFun t := a * t
  map_zero' := mul_zero a
  map_add' x y := mul_add a x y

/-- The set-theoretic range of multiplication and the range of its bundled
additive endomorphism have the same underlying residues. -/
def mulRangeEquivAddRange (a : ZMod d) :
    {y : ZMod d // y ∈ Set.range (fun t : ZMod d ↦ a * t)} ≃
      (mulAddHom a).range where
  toFun y := ⟨y.1, by
    rcases y.2 with ⟨t, ht⟩
    exact ⟨t, ht⟩⟩
  invFun y := ⟨y.1, by
    rcases y.2 with ⟨t, ht⟩
    exact ⟨t, ht⟩⟩
  left_inv y := by
    apply Subtype.ext
    rfl
  right_inv y := by
    apply Subtype.ext
    rfl

/-- The zero fibre of multiplication and the kernel of the bundled additive
endomorphism have the same underlying residues. -/
def mulZeroFiberEquivKernel (a : ZMod d) :
    {t : ZMod d // a * t = 0} ≃ (mulAddHom a).ker where
  toFun t := by
    refine ⟨t.1, ?_⟩
    change a * t.1 = 0
    exact t.2
  invFun t := by
    refine ⟨t.1, ?_⟩
    have ht := t.2
    change a * t.1 = 0 at ht
    exact ht
  left_inv t := by
    apply Subtype.ext
    rfl
  right_inv t := by
    apply Subtype.ext
    rfl

/-- Translation by one chosen solution identifies an attainable affine fibre
with the zero fibre of multiplication by `a`.  Both maps are displayed in
coordinates: `t ↦ t - t₀` and `k ↦ t₀ + k`. -/
def affineFiberEquivZeroFiber (b a t₀ y : ZMod d)
    (ht₀ : b + a * t₀ = y) :
    {t : ZMod d // b + a * t = y} ≃ {k : ZMod d // a * k = 0} where
  toFun t := by
    refine ⟨t.1 - t₀, ?_⟩
    rw [mul_sub, sub_eq_zero]
    exact add_left_cancel (t.2.trans ht₀.symm)
  invFun k := by
    refine ⟨t₀ + k.1, ?_⟩
    rw [mul_add, k.2, add_zero]
    exact ht₀
  left_inv t := by
    apply Subtype.ext
    dsimp
    abel
  right_inv k := by
    apply Subtype.ext
    dsimp
    abel

variable [NeZero d]

/-- Reducing the literal integer multiplier modulo `d` does not change its
gcd with `d`.  The right side is the ordinary integer gcd and therefore keeps
the sign of the literal multiplier out of the statement in the standard way. -/
theorem multiplierResidueGcd_eq_intGcd (B : BranchData d) (i : Fin d) :
    Nat.gcd d (B.multiplier i : ZMod d).val =
      Int.gcd (d : ℤ) (B.multiplier i) := by
  rw [Int.gcd_def, Int.natAbs_natCast]
  have h := Int.gcd_emod (B.multiplier i) (d : ℤ)
  rw [← ZMod.val_intCast] at h
  simp only [Int.gcd_def, Int.natAbs_natCast] at h
  calc
    Nat.gcd d (B.multiplier i : ZMod d).val =
        Nat.gcd (B.multiplier i : ZMod d).val d := Nat.gcd_comm _ _
    _ = Nat.gcd (B.multiplier i).natAbs d := h
    _ = Nat.gcd d (B.multiplier i).natAbs := Nat.gcd_comm _ _

/-- Exact cardinality of the multiplication range in `ZMod d`. -/
theorem card_mul_range (a : ZMod d) :
    Nat.card {y : ZMod d // y ∈ Set.range (fun t : ZMod d ↦ a * t)} =
      d / Nat.gcd d a.val := by
  calc
    _ = Nat.card (AddSubgroup.zmultiples a) :=
      Nat.card_congr (mulRangeEquivZMultiples a)
    _ = addOrderOf a := by
      rw [Nat.card_eq_fintype_card, Fintype.card_zmultiples]
    _ = addOrderOf (a.val : ZMod d) := by
      rw [ZMod.natCast_zmod_val]
    _ = d / Nat.gcd d a.val := by
      rw [ZMod.addOrderOf_coe a.val (NeZero.ne d), Nat.gcd_comm]

/-- Exact cardinality of the zero fibre of multiplication by `a` in
`ZMod d`. -/
theorem card_mul_zero_fiber (a : ZMod d) :
    Nat.card {t : ZMod d // a * t = 0} = Nat.gcd d a.val := by
  let f : ZMod d →+ ZMod d := mulAddHom a
  let g := Nat.gcd d a.val
  have hd : 0 < d := Nat.pos_of_ne_zero (NeZero.ne d)
  have hgd : g ∣ d := Nat.gcd_dvd_left d a.val
  have hgpos : 0 < g := Nat.gcd_pos_of_pos_left a.val hd
  have hgle : g ≤ d := Nat.le_of_dvd hd hgd
  have hquotpos : 0 < d / g := Nat.div_pos hgle hgpos
  have hrange : Nat.card f.range = d / g := by
    calc
      Nat.card f.range =
          Nat.card {y : ZMod d // y ∈ Set.range (fun t : ZMod d ↦ a * t)} :=
        Nat.card_congr (mulRangeEquivAddRange a).symm
      _ = d / g := card_mul_range a
  have hproduct : Nat.card f.ker * Nat.card f.range = Nat.card (ZMod d) := by
    rw [← AddSubgroup.index_ker f]
    exact f.ker.card_mul_index
  have hkernel : Nat.card f.ker = g := by
    apply Nat.eq_of_mul_eq_mul_right hquotpos
    calc
      Nat.card f.ker * (d / g) = d := by
        rw [← hrange, hproduct, Nat.card_zmod]
      _ = g * (d / g) := (Nat.mul_div_cancel' hgd).symm
  calc
    Nat.card {t : ZMod d // a * t = 0} = Nat.card f.ker :=
      Nat.card_congr (mulZeroFiberEquivKernel a)
    _ = g := hkernel

/-- Exact number of attainable next digits for an arbitrary multiplier.

The gcd is computed from the literal residue of the integer multiplier in
`ZMod d`; `multiplierResidueGcd_eq_intGcd` above identifies it with the usual
integer gcd. -/
theorem card_nextDigit_range (B : BranchData d) (i : Fin d) :
    Nat.card {y : ZMod d // y ∈ Set.range (nextDigit B i)} =
      d / Nat.gcd d (B.multiplier i : ZMod d).val := by
  let a : ZMod d := B.multiplier i
  let b : ZMod d := B.branchValue i
  calc
    Nat.card {y : ZMod d // y ∈ Set.range (nextDigit B i)} =
        Nat.card {y : ZMod d // y ∈ Set.range (fun t : ZMod d ↦ b + a * t)} := by
          rfl
    _ = Nat.card {y : ZMod d // y ∈ Set.range (fun t : ZMod d ↦ a * t)} :=
      Nat.card_congr (translateMulRangeEquiv b a).symm
    _ = d / Nat.gcd d a.val := card_mul_range a

/-- The range-cardinality formula stated using the ordinary gcd of the literal
integer multiplier. -/
theorem card_nextDigit_range_literal (B : BranchData d) (i : Fin d) :
    Nat.card {y : ZMod d // y ∈ Set.range (nextDigit B i)} =
      d / Int.gcd (d : ℤ) (B.multiplier i) := by
  rw [card_nextDigit_range, multiplierResidueGcd_eq_intGcd]

/-- Every attainable next digit has exactly
`gcd d (m_i mod d)` input lifts.  The attainability hypothesis is necessary:
an unattainable next digit has an empty fibre. -/
theorem card_nextDigit_fiber (B : BranchData d) (i : Fin d) (y : ZMod d)
    (hy : y ∈ Set.range (nextDigit B i)) :
    Nat.card {t : ZMod d // nextDigit B i t = y} =
      Nat.gcd d (B.multiplier i : ZMod d).val := by
  rcases hy with ⟨t₀, ht₀⟩
  let a : ZMod d := B.multiplier i
  let b : ZMod d := B.branchValue i
  have ht₀' : b + a * t₀ = y := by
    simpa [a, b, nextDigit] using ht₀
  calc
    Nat.card {t : ZMod d // nextDigit B i t = y} =
        Nat.card {t : ZMod d // b + a * t = y} := by rfl
    _ = Nat.card {k : ZMod d // a * k = 0} :=
      Nat.card_congr (affineFiberEquivZeroFiber b a t₀ y ht₀')
    _ = Nat.gcd d a.val := card_mul_zero_fiber a

/-- The fibre-cardinality formula stated using the ordinary gcd of the literal
integer multiplier. -/
theorem card_nextDigit_fiber_literal (B : BranchData d) (i : Fin d)
    (y : ZMod d) (hy : y ∈ Set.range (nextDigit B i)) :
    Nat.card {t : ZMod d // nextDigit B i t = y} =
      Int.gcd (d : ℤ) (B.multiplier i) := by
  rw [card_nextDigit_fiber B i y hy, multiplierResidueGcd_eq_intGcd]

/-- A unit multiplier gives all `d` possible next digits. -/
theorem card_nextDigit_range_of_isUnit (B : BranchData d) (i : Fin d)
    (hunit : IsUnit (B.multiplier i : ZMod d)) :
    Nat.card {y : ZMod d // y ∈ Set.range (nextDigit B i)} = d := by
  rw [card_nextDigit_range]
  have hcoprime : Nat.Coprime (B.multiplier i : ZMod d).val d :=
    ZMod.val_coe_unit_coprime hunit.unit
  rw [Nat.gcd_comm, hcoprime.gcd_eq_one, Nat.div_one]

end CollatzReconstruction.GeneralizedResidueItinerary
